language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # release tags

notifications:
  - email: false

jobs:
  allow_failures:
    - julia: nightly
