name: Run tests

on: [push, pull_request]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0', '1.1', '1.3', '1.4', '1.5', 'nightly']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@master
      - name: "Run tests"
        uses: julia-actions/julia-runtest@master

      - name: "Test one reverse dependency: Nemo"
        env:
          JULIA_PROJECT: revdeps
        run: |
          julia -e 'using Pkg; Pkg.develop(PackageSpec(path=Base.pwd())); Pkg.build("LoadFlint");'
          julia -e 'using Pkg; Pkg.add("Nemo"); Pkg.build("Nemo"); Pkg.test("Nemo");'
        if: ${{ matrix.julia-version == '1.0' || matrix.julia-version == '1.4' && matrix.os == 'macOS-latest' }}

      - name: "Test reverse dependencies"
        env:
          JULIA_PROJECT: revdeps
        run: |
          julia -e 'using Pkg; Pkg.develop(PackageSpec(path=Base.pwd())); Pkg.build("LoadFlint");'
          julia -e 'using Pkg; Pkg.add("Nemo"); Pkg.build("Nemo");'
          julia -e 'using Pkg; Pkg.test("Nemo");'
          julia -e 'using Pkg; Pkg.add("Polymake"); Pkg.build("Polymake");'
          julia -e 'using Pkg; Pkg.test("Polymake");'
          julia -e 'using Polymake; c = polytope.cube(3); using Nemo; CC, s = Nemo.PolynomialRing(ComplexField(256), "s"); println(s);'
        if: ${{ matrix.julia-version == '1.5' }}
